version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.3
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.2
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    volumes:
      # Change which Logstash pipeline to load here by uncommenting ONE of the 'pipeline' volume mounts
      - ./logstash/pipeline/file.conf:/usr/share/logstash/pipeline/file.conf
      # - ./logstash/pipeline/mysql.conf:/usr/share/logstash/pipeline/mysql.conf
      # - ./logstash/pipeline/s3.conf:/usr/share/logstash/pipeline/s3.conf
      # - ./logstash/pipeline/kafka.conf:/usr/share/logstash/pipeline/kafka.conf
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/data/access_log:/usr/share/logstash/data/access_log:ro
      - ./mysql/:/tmp/java
  
  db:
    image: mysql/mysql-server:5.7.20
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./movie-data/ml-100k:/tmp/data
    networks:
      - elk
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - elk

  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "kafka-logs"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./logstash/data:/tmp/data
    depends_on:
      - zookeeper
    networks:
      - elk

networks:

  elk:
    driver: bridge